### ISSUE TITLE
I have a installation problem

### ISSUE THREAD

**Issue by emircanerkul** [mettiuss/bus#1]
Hi @MettiusHyper, I successfully connected my mi7 band and I was also able to install watches with zeus bridge but when installing your app it gives an error

```
bridge$ connect
bridge$ info  successfully connected to app-Android.
bridge$ install
info  building...
[PNG2TGA] Converting PNG files...
[PNG2TGA] 2 files, 40ms, done!
[QJSC] Compiling JS files...
[QJSC] 3 files, 48ms, done!
info  getting package...
bridge$ info  Start install lite app
info  Install lite app result: bluetooth channel is not available. Please try again later
```

Any idea how to solve it?
My other question is how can I install bin file directly to the band without using an additional app except for Zepp?

Thank you

**Comment by mettiuss** [comment]
Hello,
I unfortunately don't have an answer to these questions, when I developed the app I could not find much in the official Zepp documentation, particularly around this theme.

I tried to install the Zepp Simulator but it didn't support the mi band 7, has this changed? have they added support?

When I was writing the code I ended up compiling a bin file and installing the app using this: https://play.google.com/store/apps/details?id=asn.ark.miband7.

Were you able to install some other mi band 7 apps?
I will be trying out the developer bridge mode to see if I can get it up and running on my machine and if I can find the issue.

**Comment by emircanerkul** [comment]
@MettiusHyper It is not supported officially but you can try this https://prog.world/we-write-an-application-on-mi-band-7-with-a-service-part/ Mi 7 and Amazfit Band 7 quite similar, you can trick the app unfortunately it is the only way.

I also saw this app and I tried and hated it due to lots of ads.

I am able to install my custom watch faces with *Zepp but not miniapps (It gives Bluetooth error). And I'm testing on a real mi 7 device (you can think like amazfit band 7) not a simulator in this case.

**Comment by mettiuss** [comment]
I did some searches and I might have found the reason for the error.

In this Chinese website https://www.bilibili.com/read/cv21256084/ is described a process very similar to the one described in your link and in the notes there is this point:
2. The original official package can also be bound, but the developer mode cannot be used, and it will prompt "Bluetooth channel is not available. Please try again later."

Maybe you can check if this solves the issue, I still have not been able to try the app myself

**Comment by emircanerkul** [comment]
@MettiusHyper Thank you, but APK links are broken in the article also I do not trust such edited apk packages because these apps gets almost all permissions. If there are open-source forks that would be great. I can build by my self.

**Comment by emircanerkul** [comment]
I used https://codeberg.org/Freeyourgadget/Gadgetbridge
