### ISSUE TITLE
Black screen when launching the app

### ISSUE THREAD

**Issue by 0x766C70** [mettiuss/bus#2]
First, thanks for that example !

I have successfully installed it but when on the band, I can see the Bus icon but if I clic on it I have a black screen. Wondering if I may have missed smth.

**Comment by mettiuss** [comment]
Hello,

Have you set the data.json file? You should create it under page/data.json following the template in page/data-structure.text
Unfortunately the app does not fetch data from the web (band limitation) so it needs to be set manually.

Let me know if you have any issues with this
